name: Docker Image CI

on:
  push:
    tags: "v*"
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v1.1.1
        with:
          context: .
          file: ./Dockerfile
          registry: trenchdevs/trenchdevs
          tags: latest
          tag_with_ref: true
          tag_with_sha: true
          push: true

